---
# tasks file for web
    - name: install apache web server
      yum:
        name: httpd, git
        state: present
        update_cache: true
      tags:
        - base
    - name: install packages
      yum:
        name: 
          - php
          - php-mysql
        state: present
        update_cache: true
      notify: restart apache web server
      tags:
        - base
    - name: start and enable apache web service
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - base
    - name: deploy index.php
      git:
        repo: "{{ repository }}"
        dest: "{{ document_root_path }}"
      tags:
        - content
    - name: vhost config block
      block:
      - name: Copy vhost config
        copy:
          src: ansible_site.conf
          dest: "{{ vhost_config_file }}"
          owner: root
          group: root
          mode: 0644
        notify: restart apache web server
      - name: check configuration validity
        command: httpd -t
      rescue:
      - name: remove bad virtual host condiguration
        file:
          path: "{{ vhost_config_file }}"
          state: absent
      - name: rolling back - ending playbook
        fail:
          msg: "Confguration file is not valid, please check that before re-running the playbook."
      tags:
        - vhost
    - name: configure httpd.conf
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: "^IncludeOptional"
        line: "IncludeOptional conf.d/*.conf"
      notify: restart apache web server
      tags:
        - vhost
    - name: install hello world script with db
      copy:
        src: db.php
        dest: "{{ document_root_path }}db.php"
        mode: 0755
      tags:
        - content
    - name: allow http traffic
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
      tags:
        - security
        - firewall